# Generated by Django 5.0.7 on 2024-10-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstates', '0002_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.PositiveBigIntegerField()),
                ('category', models.CharField(max_length=255)),
                ('p_id', models.CharField(max_length=50)),
            ],
        ),
    ]
